global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'mohamedhossnyaboelhana@gmail.com'
  smtp_auth_username: 'mohamedhossnyaboelhana@gmail.com'
  smtp_auth_password: 'qkuuiehakquntkzr'
  smtp_require_tls: true

route:
  receiver: "gmail-alert"

receivers:
  - name: "gmail-alert"
    email_configs:
      - to: "mohamedhossnyaboelhana@gmail.com"