global:
  scrape_interval: 5s
  scrape_timeout: 3s

scrape_configs:
  - job_name: "url-shortener"
    static_configs:
      - targets: ["url-shortener:5000"]
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"      